version: '3.8'

services:
  docker-login:
    image: alpine:latest
    environment:
      - DOCKER_CLI_ACI=1

  HoaPortalApp.api:
    image: ${DOCKER_REGISTRY-}HoaPortalApp-api
    build:
      context: .
      dockerfile: HoaPortalApp.Api/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - docker-login

  HoaPortalApp.mvc:
    image: ${DOCKER_REGISTRY-}HoaPortalApp-mvc
    build:
      context: .
      dockerfile: HoaPortalApp.Mvc/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - docker-login
      - HoaPortalApp.api
